name: CheckIn
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        env:
          issues: "${{ github.event.issue.body }}"
          user: "${{ github.event.issue.user.login }}"
          flag: "${{ secrets.FLAG }}"
        run: |
          echo "$user:$issues" >> issues
          git config user.name Zchengwu
          git config user.email 297896036@qq.com
          git add .
          git commit -m "add a new issue"
          git push
